name: Build Redox ISO

on:
  push:
    tags:
      - '*.*.*'

defaults:
  run:
    working-directory: ./tryredox

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get repo
        uses: actions/checkout@v2
      - name: Show directory
        run: ls
      - name: Get build requirements & source
        run: curl -sf https://gitlab.redox-os.org/redox-os/redox/raw/master/bootstrap.sh -o bootstrap.sh && bash -e bootstrap.sh
      - name: Show files
        run: echo "Base" && ls && echo "Redox" && ls redox/
      - name: Build
        run: cd redox && make -j $(nproc) all
      - name: ISO time
        run: cd redox && make iso
      - name: Release output files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tryredox/redox/build/*.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}